#!/usr/bin/env node
/**
 * Pulse Icon Asset Pipeline – Smart Grid Engine
 *
 * Reads input/master_icons.png (a 2D sprite sheet of 24×24 icons),
 * validates that icons are packed left-to-right, top-to-bottom with no gaps,
 * and writes:
 *   output/icons.h    – C++ PROGMEM header for ESP32 / TFT_eSPI
 *   output/icons.scss – SCSS classes using CSS mask-position
 */

'use strict';

const path = require('path');
const fs   = require('fs');
const { Jimp } = require('jimp');

const ICON_SIZE   = 24;
const INPUT_FILE  = path.resolve(__dirname, '../input/master_icons.png');
const JSON_FILE   = INPUT_FILE.replace(/\.png$/i, '.json');
const OUTPUT_DIR  = path.resolve(__dirname, '../output');
const CPP_FILE    = path.join(OUTPUT_DIR, 'icons.h');
const SCSS_FILE   = path.join(OUTPUT_DIR, 'icons.scss');

// ─── helpers ────────────────────────────────────────────────────────────────

/**
 * Pack an array of 576 pixel-alpha values (0 or 1) into 72 bytes, MSB first.
 * @param {number[]} bits – array of 576 values (1 = solid, 0 = transparent)
 * @returns {string} comma-separated hex byte literals, e.g. "0xFF, 0x00, ..."
 */
function packBits(bits) {
  const bytes = [];
  for (let i = 0; i < ICON_SIZE * ICON_SIZE; i += 8) {
    let byte = 0;
    for (let b = 0; b < 8; b++) {
      byte = (byte << 1) | (bits[i + b] ? 1 : 0);
    }
    bytes.push('0x' + byte.toString(16).toUpperCase().padStart(2, '0'));
  }
  return bytes.join(', ');
}

/**
 * Build the shared file-header comment block used by both output files.
 * @param {number} imgWidth
 * @param {number} imgHeight
 * @param {number} iconCount
 * @param {number} trailingEmpty
 * @returns {string[]} array of comment lines
 */
function buildFileHeader(imgWidth, imgHeight, iconCount, trailingEmpty) {
  return [
    '// Auto-generated by Pulse Icon Asset Pipeline',
    `// Source: ${imgWidth}x${imgHeight} sprite sheet, ${ICON_SIZE}x${ICON_SIZE} icons`,
    `// Total icons: ${iconCount}  (${trailingEmpty} trailing empty cells)`,
  ];
}

/**
 * Convert a human-readable icon name to a UPPER_SNAKE_CASE constant name.
 * @param {string} name – e.g. "battery empty"
 * @returns {string} – e.g. "BATTERY_EMPTY"
 */
function toConstName(name) {
  return name.trim().toUpperCase().replace(/\s+/g, '_');
}

// ─── main ───────────────────────────────────────────────────────────────────

async function main() {
  // 1. Load and validate the input image
  if (!fs.existsSync(INPUT_FILE)) {
    console.error(`ERROR: Input file not found: ${INPUT_FILE}`);
    console.error('Place your sprite sheet at input/master_icons.png and re-run npm run build.');
    process.exit(1);
  }

  let image;
  try {
    image = await Jimp.read(INPUT_FILE);
  } catch (err) {
    console.error(`ERROR: Failed to read image: ${err.message}`);
    process.exit(1);
  }

  const imgWidth  = image.bitmap.width;
  const imgHeight = image.bitmap.height;

  if (imgWidth % ICON_SIZE !== 0 || imgHeight % ICON_SIZE !== 0) {
    console.error(
      `ERROR: Image dimensions ${imgWidth}×${imgHeight} are not multiples of ${ICON_SIZE}.`
    );
    process.exit(1);
  }

  const cols       = imgWidth  / ICON_SIZE;
  const rows       = imgHeight / ICON_SIZE;
  const totalCells = cols * rows;

  console.log('');
  console.log('╔══════════════════════════════════════════╗');
  console.log('║     Pulse Icon Asset Pipeline  v1.0      ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log('');
  console.log(`  Input  : ${INPUT_FILE}`);
  console.log(`  Image  : ${imgWidth}×${imgHeight} px`);
  console.log(`  Grid   : ${cols} cols × ${rows} rows = ${totalCells} cells`);
  console.log('');

  // 1b. Optionally load icon name→index map from a companion JSON file
  let iconNames = null;
  if (fs.existsSync(JSON_FILE)) {
    try {
      iconNames = JSON.parse(fs.readFileSync(JSON_FILE, 'utf8'));
      console.log(`  Names   : ${JSON_FILE} (${Object.keys(iconNames).length} named icons)`);
      console.log('');
    } catch (err) {
      console.warn(`WARNING: Could not parse ${JSON_FILE}: ${err.message}`);
    }
  }

  // 2. Scan every cell and collect bit patterns + emptiness flags
  /** @type {{ bits: number[], isEmpty: boolean, x: number, y: number }[]} */
  const cells = [];

  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < cols; col++) {
      const x = col * ICON_SIZE;
      const y = row * ICON_SIZE;

      const bits = [];
      let isEmpty = true;

      for (let py = y; py < y + ICON_SIZE; py++) {
        for (let px = x; px < x + ICON_SIZE; px++) {
          const rgba  = image.getPixelColor(px, py);
          // Jimp stores color as 0xRRGGBBAA (big-endian 32-bit)
          const alpha = (rgba >>> 0) & 0xFF;
          const solid = alpha > 0 ? 1 : 0;
          bits.push(solid);
          if (solid) isEmpty = false;
        }
      }

      cells.push({ bits, isEmpty, x, y });
    }
  }

  // 3. Enforce no-gap rule: once an empty cell is found, all remaining cells
  //    must also be empty (trailing padding only — no gaps in the middle).
  let firstEmptyIndex = -1;
  for (let i = 0; i < cells.length; i++) {
    if (cells[i].isEmpty) {
      if (firstEmptyIndex === -1) firstEmptyIndex = i;
    } else if (firstEmptyIndex !== -1) {
      // Non-empty cell found after a gap → error
      const gapRow = Math.floor(firstEmptyIndex / cols);
      const gapCol = firstEmptyIndex % cols;
      console.error('ERROR: Gap detected in the icon grid.');
      console.error(
        `  Cell (col ${gapCol}, row ${gapRow}) is empty but is followed by a non-empty cell.`
      );
      console.error(
        '  Icons must be packed continuously left-to-right, top-to-bottom with no empty cells in the middle.'
      );
      process.exit(1);
    }
  }

  // 4. Split into icon cells (before first empty) and trailing empty cells
  const iconCells     = firstEmptyIndex === -1 ? cells : cells.slice(0, firstEmptyIndex);
  const trailingEmpty = firstEmptyIndex === -1 ? 0 : cells.length - firstEmptyIndex;
  const iconCount     = iconCells.length;

  // 5. Build output/icons.h
  const cppLines = [];
  cppLines.push('#pragma once');
  cppLines.push('#include <pgmspace.h>');
  cppLines.push('');
  cppLines.push(...buildFileHeader(imgWidth, imgHeight, iconCount, trailingEmpty));
  cppLines.push('');
  cppLines.push('namespace PulseIcons {');
  cppLines.push('');

  for (let i = 0; i < iconCells.length; i++) {
    cppLines.push(
      `const unsigned char icon_${i}[${ICON_SIZE * ICON_SIZE / 8}] PROGMEM = { ${packBits(iconCells[i].bits)} };`
    );
  }

  cppLines.push('');
  const ptrList = iconCells.map((_, i) => `icon_${i}`).join(', ');
  cppLines.push(
    `const unsigned char* const all_icons[${iconCount}] PROGMEM = { ${ptrList} };`
  );

  if (iconNames) {
    cppLines.push('');
    cppLines.push('// Icon name constants');
    for (const [name, index] of Object.entries(iconNames)) {
      cppLines.push(`constexpr uint8_t ${toConstName(name)} = ${index};`);
    }
  }

  cppLines.push('');
  cppLines.push('} // namespace pulse_icons');
  cppLines.push('');

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(CPP_FILE, cppLines.join('\n'), 'utf8');

  // 6. Build output/icons.scss
  const scssLines = [];
  scssLines.push(...buildFileHeader(imgWidth, imgHeight, iconCount, trailingEmpty));
  scssLines.push('');
  scssLines.push('.icon {');
  scssLines.push(`  width: ${ICON_SIZE}px;`);
  scssLines.push(`  height: ${ICON_SIZE}px;`);
  scssLines.push("  mask-image: url('/assets/master_icons.png');");
  scssLines.push('  mask-repeat: no-repeat;');
  scssLines.push('  display: inline-block;');
  scssLines.push('}');
  scssLines.push('');

  for (let i = 0; i < iconCells.length; i++) {
    const { x, y } = iconCells[i];
    const xStr = x === 0 ? '0' : `-${x}px`;
    const yStr = y === 0 ? '0' : `-${y}px`;
    scssLines.push(`.icon-${i} { mask-position: ${xStr} ${yStr}; }`);
  }

  scssLines.push('');

  fs.writeFileSync(SCSS_FILE, scssLines.join('\n'), 'utf8');

  // 7. Summary
  console.log(`  Processing complete:`);
  console.log(`    ✔  Icons exported          : ${iconCount}`);
  console.log(`    ✔  Trailing empty cells    : ${trailingEmpty}`);
  console.log('');
  console.log(`  Output files:`);
  console.log(`    → ${CPP_FILE}`);
  console.log(`    → ${SCSS_FILE}`);
  console.log('');
}

main().catch(err => {
  console.error('Unexpected error:', err);
  process.exit(1);
});

